#Прописываем репозиторий для скачивания vagrant box centos 7
ENV['VAGRANT_SERVER_URL'] = 'http://vagrant.elab.pro'

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"  # Используем Centos 7
  config.vm.hostname = "selinux"      # Имя виртуальной машины

  # Настройки ресурсов
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 8192   # 8 ГБ оперативной памяти
    vb.cpus = 4        # 4 ядра CPU
  end

  # Настройка сети 
  config.vm.network "forwarded_port", guest: 4881, host: 4881

#Обновление репозиториев 
config.vm.provision "OS update", type: "shell", path: "os_update.sh"

  config.vm.provision "shell", inline: <<-SHELL
    # Обновление системы

    # Установка необходимых пакетов
          yum install -y epel-release
          yum install -y nginx
          yum install -y policycoreutils-python

    # Меняем порт
          sed -ie 's/:80/:4881/g' /etc/nginx/nginx.conf
          sed -i 's/listen       80;/listen       4881;/' /etc/nginx/nginx.conf
    #Стартуем nginx      
          systemctl start nginx
          systemctl status nginx

  SHELL
end
