#Прописываем репозиторий для скачивания vagrant box ubuntu 20
ENV['VAGRANT_SERVER_URL'] = 'http://vagrant.elab.pro'

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"  # Используем Ubuntu 20
  config.vm.hostname = "zfs"      # Имя виртуальной машины
  config.vm.define "ZFS"        # Имя бокса в вагранте 

  # Настройки ресурсов
  config.vm.provider "virtualbox" do |vb|
    vb.name = "zfs"  # Имя бокса в VirtualBox
    vb.memory = 4096   # 4 ГБ оперативной памяти
    vb.cpus = 4        # 4 ядра CPU
  end

# Добавляем 8 дисков 
  config.vm.disk :disk, size: "1GB", name: "disk1"
  config.vm.disk :disk, size: "1GB", name: "disk2"
  config.vm.disk :disk, size: "1GB", name: "disk3"
  config.vm.disk :disk, size: "1GB", name: "disk4"
  config.vm.disk :disk, size: "1GB", name: "disk5"
  config.vm.disk :disk, size: "1GB", name: "disk6"
  config.vm.disk :disk, size: "1GB", name: "disk7"
  config.vm.disk :disk, size: "1GB", name: "disk8"

# Устанавливаем  zfs
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update -y

    sudo apt-get install zfsutils-linux -y 
  SHELL

  config.vm.provision "shell", reboot: true

# Разворачиваем зеркала, тестируем сжатие, снапшоты, поиск текста

   config.vm.provision "shell", path: "zfs.sh"


end
