#Прописываем репозиторий для скачивания vagrant box ubuntu 22
ENV['VAGRANT_SERVER_URL'] = 'http://vagrant.elab.pro'
#Конфигурируем машину
MACHINES = {
    :"my-kernel-update" => {
                :box_name => "ubuntu/focal64",
                :cpus => 4,
                :memory => 8192,
              }
  }
  
  Vagrant.configure("2") do |config|
    MACHINES.each do |boxname, boxconfig|
       config.vm.define boxname do |box|
        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s
        box.vm.provider "virtualbox" do |v|
          v.memory = boxconfig[:memory]
          v.cpus = boxconfig[:cpus]
        end
      end
    end
#Запускаем обновление ядра через репозиторий убунты
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update -y

    sudo apt-get install -y linux-image-generic

    sudo reboot
  SHELL

end
